version: '2'
services:
  # Database
  mysql:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL.DATABASE=homestead"
      - "MySQL.USER=homestead"
      - "MYSQL.PASSWORD=secret"
      - "MYSQL.ROOT.PASSWORD=secret"
    ports:
      - "3306:3306"
    restart: always
  
  # Application
  laravel-env:
    build: ./dockerfiles
    depends_on:
      - mysql
    volumes:
      - ".:/var/www/SmartDoorLockingSystem"

  # Web Server
  nginx:
    image: nginx:latest
    depends_on:
      - laravel-env
    volumes:
      - ".:/var/www/SmartDoorLockingSystem"
      - "./dockerfiles/config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
    restart: always
  
  